
spring.opcua.server:
  product-uri: urn:basic:opcua
  application-name: Basic OPC UA Server
  https.enabled: false
#  authentication.token-policies: username
#  security:
#    policy: none
#server:
#  port: 8080

spring:
  profiles:
    active: @spring.profile@
#    mode: none

  application:
    name: your-service-name  # 确保与日志路径匹配
  logging:
    config: classpath:logback-spring.xml
    # 可选：覆盖日志路径（K8s 环境常用）
    # path: /data/logs/${spring.application.name}