
spring.opcua.server:
  product-uri: urn:basic:opcua
  application-name: Basic OPC UA Server
  https.enabled: false
#  authentication.token-policies: username
#  security:
#    policy: none
#server:
#  port: 8080

#    mode: none